version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hashcat
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
#  hashtopus:
#    build: ./hashtopus/
#    links:
#      - db:db
#    ports:
#      - 80:80
#    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: hashcat
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: hashcat
      PMA_HOST: db